# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: "My eval"

prompts:
  - file://prompts/code.json
  - file://prompts/test.json
  # - file://prompts/creative.json
  # - file://prompts/default.json
  # - file://prompts/math.json
  # - file://prompts/translator.json

providers:
  - id: https
    config:
      url: "http://localhost:8000/api/chat?skip_memory=true&conversation_id=promptfoo"
      method: POST
      headers:
        'accept': application/json
        Content-Type: application/json
      body: '{{ prompt }}'
      transformResponse: 'json.response'