# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: "My eval"

prompts:
  - file://prompts/prompts.txt


providers:
  - id: https
    config:
      url: "http://127.0.0.1:8000/api/chat?skip_memory=true&conversation_id=promptfoo"
      method: POST
      headers:
        Content-Type: application/json
      body:
        messages:
          - role: user
            content: "{{prompt}}"
      transformResponse: 'json.response' 